import UIKit

struct StringConstants {
    static let kLblForYou: String = "For You"
    static let kMsg: String = "**** **** **** 8395"
    static let kLblLegal: String = "Legal"
    static let k: String = ""
    static let kLblShop: String = "Shop"
    static let kMsgOnceYouAddFu: String = "Once you add Funnels to your cart they’ll appear here."
    static let kLblUfo2: String = "UFO!"
    static let kLblBarsDrinks: String = "Bars & Drinks"
    static let kMsgLocalMexicanC: String =
        "Local Mexican counter-serve chain offering tacos, burritos, nachos & more in a quirky atmosphere."
    static let kLblSavedForLater: String = "Saved for Later"
    static let kLblUfo: String = "UFO\n"
    static let kLblMenu: String = "Menu"
    static let kMsgBuy2Get1Tac2: String = "Buy 2 Get 1 Taco Free!"
    static let kLblWallet: String = "Wallet"
    static let kLblFavorites: String = "Favorites"
    static let kLbl45: String = "4.5"
    static let kLbl1122334455: String = "1122334455"
    static let kMsgYourCartIsEm: String = "Your Cart is empty."
    static let kMsg15MonthBogo: String = "$15/Month\nBoGo Ice Pops"
    static let kLblMastercard: String = "Mastercard"
    static let kLblShops: String = "Shops"
    static let kMsgShopsCityEt: String = "Shops. City. Etc. "
    static let kLblPaymentOptions: String = "Payment Options"
    static let kMsgTacos: String = "Tacos!          \nBuy 2 Get 1 Tacos\n"
    static let kLblGoToCheckout: String = "Go to Checkout"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblNotifications: String = "Notifications"
    static let kLblSaveForLater: String = "Save for Later"
    static let kLbl1Item: String = "1 Item"
    static let kMsgQuirkyMexican: String = "Quirky Mexican spot for tacos & more"
    static let kMsg35MonthBill: String =
        "$35/ Month billed on same day every month\nAvailable for Both Land & Sea Tacos\nLimit one use per day\nQR code must be presented at checkout in order to use "
    static let kLblActivities: String = "Activities"
    static let kMsg20MonthFree: String = "$20/Month\nFree Drink & 1 Side with Entree"
    static let kLblTacos2: String = "Tacos!\n"
    static let kLblTacos3: String = "Tacos!"
    static let kLbl: String = "+"
    static let kLblEditProfile: String = "Edit Profile"
    static let kLblShopNow: String = "Shop Now"
    static let kMsgBuy1Get1Ufo: String = "Buy 1 Get 1 UFO Free!"
    static let kLbl1547Reviews: String = "1547 reviews"
    static let kLblSupport: String = "Support"
    static let kMsgHyppoGourmetI2: String = "Hyppo Gourmet Ice Pops\n"
    static let kMsgBuy2Get1Tac: String = "Buy 2 Get 1 Tacos\n"
    static let kLblSearch: String = "Search"
    static let kMsgTheBlueHenCa: String =
        "The Blue Hen Cafe\n$20/Month\nFree Drink & 1 Side with Entree"
    static let kLblSignOut: String = "Sign Out"
    static let kMsgDineInTakeo: String = "Dine-in & Takeout"
    static let kMsg30Month1Fre: String = "$30/Month\n1 Free Drink with Entree"
    static let kLblMyAccount: String = "My Account"
    static let kLblAddToCart: String = "Add to Cart"
    static let kMsgLimitedToOne: String = "Limited to one use per day"
    static let kMsg30MonthBuy1: String = "$30/Month\nBuy 1 Get 1 UFO’s "
    static let kLblReciepts: String = "Reciepts"
    static let kMsgTheBlueHenCa2: String = "The Blue Hen Cafe\n"
    static let kLblFunnelGold: String = "Funnel Gold"
    static let kLblCheckout: String = "Checkout"
    static let kLblRestaurants: String = "Restaurants"
    static let kLblPaypal: String = "PayPal"
    static let kLblBarsAndDrinks: String = "Bars and Drinks"
    static let kLblDetails: String = "Details     "
    static let kMsgJoinNowAndGe: String = "Join now and get 1 month free"
    static let kMsgUfo30MonthB: String = "UFO\n$30/Month\nBuy 1 Get 1 UFO’s "
    static let kMsgPaymentPrefere: String = "Payment Preferences"
    static let kLblCart: String = "Cart"
    static let kLblFunnels: String = "Funnels"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgBurritoWorksT2: String = "Burrito Works Taco Shop\n"
    static let kMsg2: String = "**** **** **** 6246"
    static let kMsgAddPaymentMet: String = "Add Payment Method"
    static let kLblCompleteOrder: String = "Complete Order"
    static let kLbl35: String = "$35"
    static let kMsgTacos25Mont: String =
        "Tacos!\n$25/Month\nBuy 2 Get 1 Free Tacos Everytime you go"
    static let kMsgJgGmai: String = "JG********@gmail.com"
    static let kMsg40MonthBill: String =
        "$40/ Month billed on same day every month\nLimit one use per day\nQR code must be presented at checkout in order to use "
    static let kMsgBurritoWorksT4: String =
        "Burrito Works Taco Shop\nQuirky Mexican spot for tacos & more"
    static let kMsgBurritoWorksT3: String = "Burrito Works Taco Shop"
    static let kLblSettings: String = "Settings"
    static let kLblTacos: String = "Tacos!          \n"
    static let kMsgBurritoWorksT5: String = "Burrito Works Taco "
    static let kLbl40Month: String = "$40/Month"
    static let kMsg25MonthBuy2: String = "$25/Month\nBuy 2 Get 1 Free Tacos Everytime you go"
    static let kLblVisa: String = "Visa"
    static let kLblForYou2: String = "For You "
    static let kMsgHyppoGourmetI: String = "Hyppo Gourmet Ice Pops\n$15/Month\nBoGo Ice Pops"
    static let kLblExplore: String = "Explore"
    static let kLblJacobGoldman: String = "Jacob Goldman"
    static let kLbl35Month: String = "$35/Month"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsgBurritoWorksT: String =
        "Burrito Works Taco Shop\n$30/Month\n1 Free Drink with Entree"
    static let kMsgStAugustine: String = "St. Augustine, Florida"
}
